version: "3"

services:
  telegram-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=paste-telegram-token

  watcher:
    build:
      context: .
      dockerfile: uz/Dockerfile
    environment:
      - NODE_ENV=production
  mongo:
      image: "mongo:latest"
      ports:
        - 27017:27017
    rabbitmq:
      image: "rabbitmq:management"
      ports:
        - "5672:5672"
        - "15672:15672"