apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: planner
  labels:
    app: planner
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: planner
              image: loginkr/uz-booking-planner:latest
              imagePullPolicy: Always
              # env:
              #   - name: NODE_ENV
              #     value: development
              envFrom:
                - configMapRef:
                    name: amqp
                - configMapRef:
                    name: mongo
          restartPolicy: OnFailure
